proje/crm/crm_app/Areas/Admin/Controllers/SalesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Services.Contracts;

namespace crm_app.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SalesController : Controller
    {
        private readonly IServiceManager _manager;

        public SalesController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.PaymentService.GetAllPayment(true);
            return View(model);
        }
    }
}

proje/crm/crm_app/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace crm_app.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly IServiceManager _manager;

        public UserController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var users = _manager.AuthService.GetAllUsers();
            return View(users);
        }

        [HttpGet]
        public async Task<IActionResult> inactive([FromRoute(Name = "id")] string id)
        {
            await _manager.AuthService.userInActive(id);

            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> onshowcase([FromRoute(Name = "id")] string id)
        {
            await _manager.AuthService.OnShowCase(id);

            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> closeShowCase([FromRoute(Name = "id")] string id)
        {
            await _manager.AuthService.closeShowCase(id);

            return RedirectToAction("Index");
        }
    }
}

proje/crm/crm_app/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <title>@ViewData["Title"]</title>
</head>

<body>
    <div class="row">
        <div class="col-2">
            <partial name="_Navbar"></partial>
            @RenderSection("Header", false)
        </div>
        <div class="col-9">
            <main>
                @RenderBody()
            </main>
        </div>
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>

</body>

</html>

proje/crm/crm_app/Areas/Admin/Views/Shared/_Navbar.cshtml
<link rel="stylesheet" href="~/css/admin.css">
<aside>
    <div class="top">
        <div class="logo" style="margin-left: 2rem;">
            <a asp-area="" asp-action="Index" asp-controller="Home">
                <h2>Randevu<span class="primary">BUL</span></h2>
            </a>
        </div>

        <div class="close" id="close-btn">
            <span class="material-symbols-outlined">close</span>
        </div>
    </div>
    <div class="sidebar">
        <a asp-controller="Dashboard" asp-action="Index">
            <span class="material-symbols-outlined">dashboard</span>
            <h3>Panel</h3>
        </a>
        <a asp-controller="User" asp-action="Index" class="">
            <span class="material-symbols-outlined">person</span>
            <h3>Kullanıcılar</h3>
        </a>
        <a asp-controller="Category" asp-action="Index">
            <span class="material-symbols-outlined">orders</span>
            <h3>Kategoriler</h3>
        </a>
        <a asp-controller="Sales" asp-action="Index">
            <span class="material-symbols-outlined">monitoring</span>
            <h3>Satışlar</h3>
        </a>
        <a asp-controller="Contact" asp-action="Index">
            <span class="material-symbols-outlined">mail</span>
            <h3>Mesajlar</h3>
        </a>
        <a asp-action="Index" asp-controller="Product">
            <span class="material-symbols-outlined">inventory_2</span>
            <h3>Paketler</h3>
        </a>
        <a asp-action="Index" asp-controller="Settings">
            <span class="material-symbols-outlined">settings</span>
            <h3>Site Ayaları</h3>
        </a>
        <a asp-area="" asp-action="Logout" asp-controller="Account">
            <span class="material-symbols-outlined">Logout</span>
            <h3>Çıkış Yap</h3>
        </a>
    </div>
</aside>