proje/crm/crm_app/Controllers/ProfileController.cs
using System.Globalization;
using crm_app.Models;
using Entities.Dtos;
using Entities.Models;
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Model.V2;
using Iyzipay.Model.V2.Subscription;
using Iyzipay.Request;
using Iyzipay.Request.V2.Subscription;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Services.Contracts;

namespace crm_app.Controllers
{
    [Authorize(Roles = "User")]
    public class ProfileController : Controller
    {
        private readonly IServiceManager _manager;
        private readonly UserManager<AppUser> _userManager;

        public ProfileController(IServiceManager manager, UserManager<AppUser> userManager)
        {
            _manager = manager;
            _userManager = userManager;
        }

        private SelectList GetDateSelectList()
        {
            return new SelectList(_manager.MeetService.GetAllMeetSlots(false), "id", "Date");
        }
        private SelectList GetCategoriesSelectList()
        {
            return new SelectList(_manager.CategoryService.GetAllCategory(false), "CategoryID", "CategoryName", "1");
        }

        public async Task<IActionResult> Index()
        {
            ViewData["Title"] = "Profilim";

            var user = await _userManager.GetUserAsync(User);

            return View(user);
        }


        public async Task<IActionResult> myMeet()
        {
            ViewData["Title"] = "Profilim/Randevular";
            var user = await _userManager.GetUserAsync(User);
            var id = user?.Id;
            var model = _manager.MeetService.getMeet(id);

            return View(model);
        }

        [HttpPost]
        public IActionResult Complete([FromForm] int id)
        {
            _manager.MeetService.Complete(id);
            return RedirectToAction("myMeet");
        }

        public async Task<IActionResult> pastMeet()
        {
            ViewData["Title"] = "Profilim/Geçmiş Randevular";
            var user = await _userManager.GetUserAsync(User);
            var id = user?.Id;

            var model = _manager.MeetService.PastMeets(id);
            return View(model);
        }


        public async Task<IActionResult> setting()
        {
            ViewData["Title"] = "Profilim/Ayalar";
            var user = await _userManager.GetUserAsync(User);
            ViewBag.Categories = GetCategoriesSelectList();
            return View(user);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> setting([FromForm] AppUserDtoUpdate userDtoUpdate, IFormFile file)
        {


            string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", file.FileName);

            using (var stream = new FileStream(path, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }
            var user = await _userManager.GetUserAsync(User);
            if (ModelState.IsValid)
            {
                userDtoUpdate.FirmaLogo = String.Concat("/images/", file.FileName);
                await _manager.AuthService.Update(userDtoUpdate, user.Id);
                return RedirectToAction("Index");
            }
            return View();
        }


        public ActionResult resetpassword()
        {
            ViewData["Title"] = "Profilim/Şifre Yenileme";
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> resetpassword([FromForm] ResetPasswordDto passwordDto)
        {
            var user = await _userManager.GetUserAsync(User);
            var id = user?.Id;
            var result = await _manager.AuthService.ResetPassword(passwordDto, id);
            return result.Succeeded
             ? RedirectToAction("Index")
             : View();
        }

        public IActionResult configureproduct()
        {
            ViewData["Title"] = "Profilim/Üyelik";
            var model = _manager.ProductService.GetAllProduct(false);
            return View(model);
        }

        public IActionResult configurepay([FromRoute(Name = "id")] int id)
        {
            ViewData["Title"] = "Ödeme Sayfası";
            var model = _manager.ProductService.GetOneProduct(id, false);
            ViewBag.product = model;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> configurepay([FromForm] PaymentDtoForCreation paymentDto)
        {
            Random random = new Random();
            int basketID = random.Next(1000000, 10000000);
            var user = await _userManager.GetUserAsync(User);
            var userId = user?.Id;
            paymentDto.UserID = userId;
            var ipadress = HttpContext.Connection.RemoteIpAddress?.MapToIPv4().ToString();
            Entities.Models.Product? product = _manager.ProductService.GetOneProduct(paymentDto.productId, false);
            if (ModelState.IsValid)
            {

                Options options = new Options();
                options.ApiKey = "sandbox-Zo3rjTvrIU8bjp76BAMM9zYzWcIKNLR4";
                options.SecretKey = "sandbox-sv7yJDZkWmTCF0qZNrLCku3yCdqSDHe0";
                options.BaseUrl = "https://sandbox-api.iyzipay.com";


                CreatePaymentRequest request = new CreatePaymentRequest();
                request.Locale = Locale.TR.ToString();
                request.ConversationId = basketID.ToString();
                request.Price = paymentDto.Amount;
                request.PaidPrice = paymentDto.Amount;
                request.Currency = Currency.TRY.ToString();
                request.Installment = 1;
                request.BasketId = basketID.ToString();
                request.PaymentChannel = PaymentChannel.WEB.ToString();
                request.PaymentGroup = PaymentGroup.PRODUCT.ToString();


                PaymentCard paymentCard = new PaymentCard();
                paymentCard.CardHolderName = paymentDto.CardHolderName;
                paymentCard.CardNumber = paymentDto.CardNumber;
                paymentCard.ExpireMonth = paymentDto.ExpirationMonth;
                paymentCard.ExpireYear = paymentDto.ExpirationYear;
                paymentCard.Cvc = paymentDto.Cvv;
                paymentCard.RegisterCard = 0;
                request.PaymentCard = paymentCard;

                Buyer buyer = new Buyer();
                buyer.Id = user?.Id;
                buyer.Name = user?.UserName;
                buyer.Surname = user?.UserName;
                buyer.GsmNumber = user?.PhoneNumber;
                buyer.Email = user?.Email;
                buyer.IdentityNumber = user?.Id;
                buyer.LastLoginDate = "";
                buyer.RegistrationDate = "";
                buyer.RegistrationAddress = user?.TamAdres;
                buyer.Ip = ipadress;
                buyer.City = user?.Şehir + "/" + user?.İlçe;
                buyer.Country = "Turkey";
                buyer.ZipCode = "";
                request.Buyer = buyer;


                Address shippingAddress = new Address();
                shippingAddress.ContactName = user?.FirmaAdi;
                shippingAddress.City = user?.Şehir;
                shippingAddress.Country = "Turkey";
                shippingAddress.Description = user?.TamAdres;
                shippingAddress.ZipCode = "";
                request.ShippingAddress = shippingAddress;


                Address billingAddress = new Address();
                billingAddress.ContactName = user?.FirmaAdi;
                billingAddress.City = user?.Şehir;
                billingAddress.Country = "Turkey";
                billingAddress.Description = user?.TamAdres;
                billingAddress.ZipCode = "";
                request.BillingAddress = billingAddress;


                List<BasketItem> basketItems = new List<BasketItem>();
                BasketItem firstBasketItem = new BasketItem();
                firstBasketItem.Id = paymentDto.Id.ToString();
                firstBasketItem.Name = product?.ProductName;
                firstBasketItem.Category1 = product?.ProductName;
                firstBasketItem.Category2 = product?.ProductName;
                firstBasketItem.ItemType = BasketItemType.PHYSICAL.ToString();
                firstBasketItem.Price = paymentDto.Amount;
                basketItems.Add(firstBasketItem);
                request.BasketItems = basketItems;

                Iyzipay.Model.Payment payment = Iyzipay.Model.Payment.Create(request, options);

                if (payment.Status == "success")
                {
                    var newPaymentDto = new PaymentDtoForCreation
                    {
                        Id = paymentDto.Id,
                        Amount = paymentDto.Amount,
                        productId = paymentDto.productId,
                        UserID = paymentDto.UserID,
                        Status = "Success",
                        PaymentMethod = "Card"
                        // Diğer gerekli alanlar burada set edilir...
                        // CardHolderName ve diğer init-only alanlar boş kalacak
                    };
                    int date = Convert.ToInt32(product?.PaketSüresi);
                    DateTime currentDate = DateTime.Now;
                    DateTime end = currentDate.AddMonths(date);
                    string baslangicTarihi = currentDate.ToString("dd/MM/yyyy");
                    string bitisTarihi = end.ToString("dd/MM/yyyy");
                    await _manager.AuthService.UserActive(userId, baslangicTarihi, bitisTarihi);
                    _manager.PaymentService.CreatePayment(newPaymentDto);
                    return RedirectToPage("/complate");
                }
                else
                {
                    return RedirectToPage("/failcomplate");
                }

            }

            return View();

proje/crm/crm_app/Controllers/SorguController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace crm_app.Controllers
{
    public class SorguController : Controller
    {
        private readonly IServiceManager _manager;

        public SorguController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var meet = new Meet();
            return View(meet);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index([FromForm] String sorguKodu)
        {
            var model = _manager.MeetService.SorguKodu(sorguKodu);
            return View(model);
        }
    }
}

proje/crm/crm_app/Controllers/firmalarController.cs
using crm_app.Models;
using Entities.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Services.Contracts;

namespace crm_app.Controllers
{
    public class firmalarController : Controller
    {
        private readonly IServiceManager _manager;
        private readonly UserManager<AppUser> _userManager;

        public firmalarController(IServiceManager manager, UserManager<AppUser> userManager)
        {
            _manager = manager;
            _userManager = userManager;
        }

        private SelectList GetDateSelectList()
        {
            return new SelectList(_manager.MeetService.GetAllMeetSlots(false).GroupBy(ms => ms.Date).Select(g => g.First()).ToList()
            , "Id", "Date");
        }
        public IActionResult Index()
        {
            ViewData["Title"] = "Firmalar";
            var model = _manager.AuthService.GetAllUsers().Where(C => C.aktive == true);
            return View(model);
        }
        public async Task<IActionResult> get([FromRoute(Name = "id")] string username, DateTime? selectedDate)
        {
            ViewData["Title"] = username;
            var model = await _userManager.FindByNameAsync(username);
            var meet = _manager.MeetService.GetMeetSlot(false, model.Id);
            ViewBag.DateSelectlist = GetDateSelectList();

            if (selectedDate.HasValue)
            {
                meet = meet.Where(m => DateTime.Parse(m.Date).Date == selectedDate.Value.Date).ToList();
            }
            var result = new RandevuViewModel
            {
                MeetSlots = meet,
                User = model,
                SelectedDate = selectedDate  // Seçilen tarihi view'a gönder
            };
            return View(result);
        }
        public IActionResult ConfigureMeeting([FromRoute(Name = "id")] int id)
        {
            ViewData["Title"] = "Randevu Oluşturma";
            var result = _manager.MeetService.GetMeeting(id, false);
            var meeting = new Meet();
            var model = new MeetPageModel()
            {
                meetSlot = result,
                meet = meeting
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ConfigureMeeting([FromForm] Meet meet)
        {

            if (ModelState.IsValid)
            {
                string sorguKodu = GenerateRandomCode(11);
                meet.sorguKodu = sorguKodu;
                _manager.MeetService.CreateMeet(meet);
                _manager.MeetService.UpdateMeetSlot(meet.MeetSlotID);
                return RedirectToAction("kayit", new { randevuKodu = sorguKodu });
            }
            return View();
        }

        public IActionResult kategori([FromRoute(Name = "id")] string name)
        {
            var category = _manager.CategoryService.GetAllCategory(false)
                   .FirstOrDefault(c => c.CategoryName == name);

            if (category == null)
            {
                // Kategori bulunamadığında bir hata sayfasına yönlendirebilir veya hata mesajı döndürebilirsiniz
                return NotFound(); // ya da uygun bir hata sayfası döndürün
            }

            // Bulunan kategori ID'sine göre kullanıcıları filtrele
            var model = _manager.AuthService.GetAllUsers()
                          .Where(u => u.categoryID == category.CategoryID).ToList();

            return View(model);
        }


        private string GenerateRandomCode(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"; // Harf ve rakamlar
            var random = new Random();
            var result = new char[length];

            for (int i = 0; i < length; i++)
            {
                result[i] = chars[random.Next(chars.Length)];
            }

            return new string(result);
        }

        public IActionResult kayit(string randevuKodu)
        {
            return View((object)randevuKodu);
        }
    }
}

proje/crm/crm_app/Views/Shared/_Footer.cshtml
<div class="container">
    <div class="row">
    </div>
    <hr class="my-4" style="border-color: rgba(255, 255, 255, 0.2);">
    <div class="text-center">
        <p>&copy;UMCBilişim Tüm Hakları Saklıdır.</p>
    </div>
</div>

proje/crm/crm_app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=Roboto:wght@500;700&display=swap"
        rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link rel="stylesheet" <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
        rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">


    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <!-- Libraries Stylesheet -->
    <link href="~/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
    <title>@ViewData["Title"]</title>
</head>

<body>
    <Header>
        <partial name="_Navbar" />
        @RenderSection("Header", false)
    </Header>
    <div class="container">
        @RenderBody()
    </div>

    <footer>
        <partial name="_Footer" />
    </footer>

    <a href="#" class="btn btn-lg btn-primary btn-lg-square rounded-0 back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/wow/wow.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/counterup/counterup.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>



    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>
</body>

</html>

proje/crm/crm_app/Views/Shared/_LoginMenu.cshtml
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{

    <div class="mt-4 mt-lg-0 me-lg-n4 py-3 px-4 bg-primary d-flex align-items-center">
        <div class="mt-4 mt-lg-0 me-lg-n4 py-3 px-4 bg-primary d-flex align-items-center">
            <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-white"
                style="width: 45px; height: 45px;">
                <i class="fa fa-user-alt text-primary"></i>
            </div>
            <div class="ms-3">
                <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index" class="mb-1 text-white">Admin Panel</a>
            </div>
        </div>
    </div>



}

@if (User.Identity.IsAuthenticated)
{
    <div class="mt-4 mt-lg-0 me-lg-n4 py-3 px-4 bg-primary d-flex align-items-center">
        <div class="mt-4 mt-lg-0 me-lg-n4 py-3 px-4 bg-primary d-flex align-items-center">
            <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-white"
                style="width: 45px; height: 45px;">
                <i class="fa fa-user-alt text-primary"></i>
            </div>
            <div class="ms-3">
                <a asp-controller="Profile" asp-action="Index" class="mb-1 text-white">Profilim</a>
             
            </div>
        </div>
    </div>


    <div class="mt-4 mt-lg-0 me-lg-n4 py-3 px-4 bg-primary d-flex align-items-center">
        <div class="mt-4 mt-lg-0 me-lg-n4 py-3 px-4 bg-primary d-flex align-items-center">
            <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-white"
                style="width: 45px; height: 45px;">
                <i class="fas fa-sign-out-alt text-primary"></i>
            </div>
            <div class="ms-3">
                
                <a asp-controller="Account" asp-action="Logout" class="mb-1 text-white">Çıkış Yap</a>
            </div>
        </div>
    </div>






}
else
{

    <div class="mt-4 mt-lg-0 me-lg-n4 py-3 px-4 bg-primary d-flex align-items-center">
        <div class="mt-4 mt-lg-0 me-lg-n4 py-3 px-4 bg-primary d-flex align-items-center">
            <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-white"
                style="width: 45px; height: 45px;">
                <i class="fas fa-sign-in-alt"></i>
            </div>
            <div class="ms-3">
                <a asp-controller="Account" asp-action="Login" class="mb-1 text-white">Giriş Yap</a>
            </div>
        </div>
    </div>

}

proje/crm/crm_app/Views/Shared/_Navbar.cshtml
<!-- Topbar Start -->
<div class="container-fluid bg-light d-none d-lg-block">
    <div class="row align-items-center top-bar">
        <div class="col-lg-3 col-md-12 text-center text-lg-start">
            <a asp-action="Index" asp-controller="Home" class="navbar-brand m-0 p-0">
                <h1 class="text-primary m-0">Randevu BUL</h1>
            </a>
        </div>
    </div>
</div>
<!-- Topbar End -->


<!-- Navbar Start -->
<div class="container-fluid nav-bar bg-light">
    <nav class="navbar navbar-expand-lg navbar-light bg-white p-3 py-lg-0 px-lg-4">

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="fa fa-bars"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav me-auto">
                <a asp-controller="Home" asp-action="Index" class="nav-item nav-link active">Anasayfa</a>
                <a href="#Paket" class="nav-item nav-link">Paketler</a>
                <a href="#About" class="nav-item nav-link">Hakkımızda</a>
                <a href="#Contact" class="nav-item nav-link">İletişim</a>
                <a asp-controller="firmalar" asp-action="Index" class="nav-item nav-link">Firmalar</a>
                <a class="nav-item nav-link" asp-controller="Sorgu" asp-action="Index">Randevu Sorgulama</a>
            </div>
            <partial name="_LoginMenu" />
        </div>
    </nav>
</div>